### PR TITLE
Cast mismatched libdns.Record/dme.Record types

### LINKED ISSUE #1: Doesn't compile - type mismatch
Hi!  I'm trying to use xcaddy to build caddy 2.8 on go 1.22.3 with the https://github.com/caddy-dns/dnsmadeeasy plugin, and it currently doesn't compile due to a type mismatch:

```
2024/05/30 12:19:16 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /home/coandco/caddy -ldflags -w -s -trimpath -tags nobadger
# github.com/libdns/dnsmadeeasy
/home/coandco/go/pkg/mod/github.com/libdns/dnsmadeeasy@v1.1.1/client.go:34:18: cannot use dmeRecord.MxLevel (variable of type int) as uint value in assignment
/home/coandco/go/pkg/mod/github.com/libdns/dnsmadeeasy@v1.1.1/client.go:36:18: cannot use dmeRecord.Priority (variable of type int) as uint value in assignment
/home/coandco/go/pkg/mod/github.com/libdns/dnsmadeeasy@v1.1.1/client.go:56:23: cannot use record.Priority (variable of type uint) as int value in assignment
/home/coandco/go/pkg/mod/github.com/libdns/dnsmadeeasy@v1.1.1/client.go:58:24: cannot use record.Priority (variable of type uint) as int value in assignment
2024/05/30 12:19:16 [INFO] Cleaning up temporary folder: /tmp/buildenv_2024-05-30-1219.1791603524
2024/05/30 12:19:16 [FATAL] exit status 1
```

It looks like the upstream libdns module may have updated the types of its `libdns.Record` type so that Priority and Weight are uints instead of ints, and so both `recordFromDmeRecord` and `dmeRecordFromRecord` fail to map the types across.  It looks like either `libdns/dnsmadeeasy` needs to cast the types, or the upstream `John-K/dnsmadeeasy` needs to update its types to synchronize with `libdns/libdns`.

### PR DESCRIPTION
**Pull request by coandco**
Currently libdns/dnsmadeeasy doesn't compile due to mismatched int/uint types.  This casts them when converting so the module can work.  Fixes #1 .

### CODE REVIEW

**Comment by Monviech** [comment]
@coandco I'm also interested in this. Can you do another commit to update all dependencies with:
```
go mod tidy
```

Afterwards when this is PR has been merged we could do a pseudo version in caddy-dns/dnsmadeeasy

Compare these PRs I made in another module:

https://github.com/libdns/netcup/pull/1
https://github.com/caddy-dns/netcup/pull/6

**Comment by Monviech** [comment]
Build works for me:

`xcaddy build --with github.com/caddy-dns/dnsmadeeasy --with github.com/libdns/dnsmadeeasy=github.com/coandco/libdns-dnsmadeeasy@08e4cf6822c015235afbab30ba6d86185a2f98a7`

**Comment by coandco** [comment]
Out of curiosity, what does it take to get a module to be downloadable on the main Caddy download page, so you don't have to build it with xcaddy yourself?

**Comment by coandco** [comment]
> Build works for me:
> 
> `xcaddy build --with github.com/caddy-dns/dnsmadeeasy --with github.com/libdns/dnsmadeeasy=github.com/coandco/libdns-dnsmadeeasy@08e4cf6822c015235afbab30ba6d86185a2f98a7`

Previous to this I was using Caddy 2.7 with lego_deprecated get certs from dnsmadeeasy.  I've now moved my setup to use Caddy 2.8 built with the above command, updated my Caddyfile to use the dns.providers.dnsmadeeasy provider, and removed the previously-cached certs from Caddy's storage.  I can confirm that Caddy is able to successfully obtain a new Let's Encrypt cert with the the code in this PR.

**Review by mholt — APPROVED** [review]
Thanks! (Sorry I broke this. The joys of pre-1.0 software...)

**Comment by mholt** [comment]
@coandco To add the Caddy plugin to the Caddy website, go to "Account" on the Caddy site and after registering/logging in, claim your package. Make sure to claim the caddy-dns module, not the libdns package.

**Pull request merged**
